from email.headerregistry import Group
from itertools import count
from operator import imod
import re
from sys import flags

texto_exemplo = "Para avaliar o nível de associação entre as variáveis selecionadas, estimou-se a matriz de correlação policórica e posteriormente verificou-se a dimensionalidade dos dados por meio da análise de componentes principais. O indicador de complexidade de gestão, baseado na Teoria de Resposta ao Item (TRI), foi estimado pelo modelo de resposta gradual de Samejima(1) considerando a existência de um único traço latente. Após a estimação dos parâmetros do modelo, o escorelatente, que aqui será denominado escore de complexidade de gestão da escola ou simplesmenteescore de complexidade, foi estimado pelo método do valor esperado à posteriori.Para facilitar a compreensão do indicador o escore de complexidade foi categorizado pormeio da definição cuidadosa de pontos de corte na escala, criando, assim, grupos de escolas comcomplexidade de gestão similar. Como procedimento prévio à definição destes pontos de corteobservou-se a distribuição empírica das escolas em relação ao escore de complexidade, osparâmetros de cada item e suas respectivas curvas características - que são úteis por indicarintervalos da escala onde cada categoria de resposta é dominante.O processo de definição dos pontos de corte foi realizado em várias etapas e direcionadopara a criação de grupos internamente homogêneos - em relação às variáveis selecionadas - efacilmente distinguíveis entre si. Após a primeira escolha dos pontos de corte observou-se aprevalência empírica das categorias de cada item selecionado dentro dos grupos formados etambém o percentual de escolas e matrículas em cada grupo. As modificações subsequentes nospontos de corte visaram a formação de grupos com características marcadamente distintas emrelação a pelo menos um dos itens e também, que em cada grupo, os itens apresentassem umacategoria ou conjunto de categorias contíguas dominantes (representando ao menos dois terços dasescolas do grupo) e as demais categorias com baixa proporção de respostas (inferior a dois terçosdas escolas do grupo).Os grupos formados foram descritos com auxílio da distribuição empírica de cada item nosmesmos. Para descrição de um grupo, as categorias ou conjunto de categorias contíguasdominantes (representando ao menos dois terços das ESCOLAS do grupo) de cada item foramdestacadas textualmente. A utilização da frequência empírica dos itens para a descrição de grupos ésugerida por Beaton e Alen(2), embora, aqui, tenha-se optado por uma abordagem comparativamentemais simples. Ressalta-se que a abordagem aqui adotada pode mostrar-se inviável para estudoscom grande número de itens, já que a descrição dos grupos se tornaria exaustiva. "

p = str(input('Digite a palavra que você quer procurar:'))
r = re.findall(p, texto_exemplo, flags=re.I)
print(r)
print('A palavra que você buscou aparece: {} vezes no texto!'.format(len(r)))